// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"errors"
	"github.com/arran4/mvcommon/cmd"

)

var _ Cmd = (*Inspect)(nil)

type Inspect struct {
	*Skill
	Flags         *flag.FlagSet
	name          string
	SubCommands   map[string]Cmd
	CommandAction func(c *Inspect) error
}

type UsageDataInspect struct {
	*Inspect
	Recursive bool
}

func (c *Inspect) Usage() {
	err := executeUsage(os.Stderr, "inspect_usage.txt", UsageDataInspect{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Inspect) UsageRecursive() {
	err := executeUsage(os.Stderr, "inspect_usage.txt", UsageDataInspect{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Inspect) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, arg)
		}
	}
	if len(remainingArgs) < 1 {
		return fmt.Errorf("expected at least 1 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument name
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.name = argVal
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("inspect failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *Skill) NewInspect() *Inspect {
	set := flag.NewFlagSet("inspect", flag.ContinueOnError)
	v := &Inspect{
		Skill:       c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}
	set.Usage = v.Usage

	v.CommandAction = func(c *Inspect) error {

		err := SkillsInspect(c.name)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("inspect failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
