// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"testing"
)

func TestRoot_Execute(t *testing.T) {
	cmd, err := NewRoot("test", "", "", "")
	if err != nil {
		t.Fatalf("Failed to create root command: %v", err)
	}

	called := false
	cmd.CommandAction = func(c *RootCmd) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--stopword")
	args = append(args, "test")
	args = append(args, "--trim")
	args = append(args, "test")
	args = append(args, "--min")
	args = append(args, "1")
	args = append(args, "--dry-run")
	args = append(args, "--interactive")

	err = cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.stopWords != "test" {
		t.Errorf("Expected stopWords to be 'test', got '%v'", cmd.stopWords)
	}
	if cmd.trim != "test" {
		t.Errorf("Expected trim to be 'test', got '%v'", cmd.trim)
	}
	if cmd.minMatch != 1 {
		t.Errorf("Expected minMatch to be 1, got '%v'", cmd.minMatch)
	}
	if cmd.dryRun != true {
		t.Errorf("Expected dryRun to be true, got '%v'", cmd.dryRun)
	}
	if cmd.interactive != true {
		t.Errorf("Expected interactive to be true, got '%v'", cmd.interactive)
	}

}
