name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Run tests
        run: go test -v ./...
